(cl:defpackage pr2_mechanism_msgs-msg
  (:use )
  (:export
   "<ACTUATORSTATISTICS>"
   "ACTUATORSTATISTICS"
   "<CONTROLLERSTATISTICS>"
   "CONTROLLERSTATISTICS"
   "<JOINTSTATISTICS>"
   "JOINTSTATISTICS"
   "<MECHANISMSTATISTICS>"
   "MECHANISMSTATISTICS"
   "<SWITCHCONTROLLERACTION>"
   "SWITCHCONTROLLERACTION"
   "<SWITCHCONTROLLERACTIONFEEDBACK>"
   "SWITCHCONTROLLERACTIONFEEDBACK"
   "<SWITCHCONTROLLERACTIONGOAL>"
   "SWITCHCONTROLLERACTIONGOAL"
   "<SWITCHCONTROLLERACTIONRESULT>"
   "SWITCHCONTROLLERACTIONRESULT"
   "<SWITCHCONTROLLERFEEDBACK>"
   "SWITCHCONTROLLERFEEDBACK"
   "<SWITCHCONTROLLERGOAL>"
   "SWITCHCONTROLLERGOAL"
   "<SWITCHCONTROLLERRESULT>"
   "SWITCHCONTROLLERRESULT"
  ))

