// Generated by gencpp from file remote_manipulation_markers/CycleGrasps.msg
// DO NOT EDIT!


#ifndef REMOTE_MANIPULATION_MARKERS_MESSAGE_CYCLEGRASPS_H
#define REMOTE_MANIPULATION_MARKERS_MESSAGE_CYCLEGRASPS_H

#include <ros/service_traits.h>


#include <remote_manipulation_markers/CycleGraspsRequest.h>
#include <remote_manipulation_markers/CycleGraspsResponse.h>


namespace remote_manipulation_markers
{

struct CycleGrasps
{

typedef CycleGraspsRequest Request;
typedef CycleGraspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CycleGrasps
} // namespace remote_manipulation_markers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_manipulation_markers::CycleGrasps > {
  static const char* value()
  {
    return "fe024696dfb3bd52cdf4e699701de6ee";
  }

  static const char* value(const ::remote_manipulation_markers::CycleGrasps&) { return value(); }
};

template<>
struct DataType< ::remote_manipulation_markers::CycleGrasps > {
  static const char* value()
  {
    return "remote_manipulation_markers/CycleGrasps";
  }

  static const char* value(const ::remote_manipulation_markers::CycleGrasps&) { return value(); }
};


// service_traits::MD5Sum< ::remote_manipulation_markers::CycleGraspsRequest> should match 
// service_traits::MD5Sum< ::remote_manipulation_markers::CycleGrasps > 
template<>
struct MD5Sum< ::remote_manipulation_markers::CycleGraspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_manipulation_markers::CycleGrasps >::value();
  }
  static const char* value(const ::remote_manipulation_markers::CycleGraspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_manipulation_markers::CycleGraspsRequest> should match 
// service_traits::DataType< ::remote_manipulation_markers::CycleGrasps > 
template<>
struct DataType< ::remote_manipulation_markers::CycleGraspsRequest>
{
  static const char* value()
  {
    return DataType< ::remote_manipulation_markers::CycleGrasps >::value();
  }
  static const char* value(const ::remote_manipulation_markers::CycleGraspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_manipulation_markers::CycleGraspsResponse> should match 
// service_traits::MD5Sum< ::remote_manipulation_markers::CycleGrasps > 
template<>
struct MD5Sum< ::remote_manipulation_markers::CycleGraspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_manipulation_markers::CycleGrasps >::value();
  }
  static const char* value(const ::remote_manipulation_markers::CycleGraspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_manipulation_markers::CycleGraspsResponse> should match 
// service_traits::DataType< ::remote_manipulation_markers::CycleGrasps > 
template<>
struct DataType< ::remote_manipulation_markers::CycleGraspsResponse>
{
  static const char* value()
  {
    return DataType< ::remote_manipulation_markers::CycleGrasps >::value();
  }
  static const char* value(const ::remote_manipulation_markers::CycleGraspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_MANIPULATION_MARKERS_MESSAGE_CYCLEGRASPS_H
