// Auto-generated. Do not edit!

// (in-package rail_manipulation_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PickupResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.executionSuccess = null;
      this.success = null;
    }
    else {
      if (initObj.hasOwnProperty('executionSuccess')) {
        this.executionSuccess = initObj.executionSuccess
      }
      else {
        this.executionSuccess = false;
      }
      if (initObj.hasOwnProperty('success')) {
        this.success = initObj.success
      }
      else {
        this.success = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PickupResult
    // Serialize message field [executionSuccess]
    bufferOffset = _serializer.bool(obj.executionSuccess, buffer, bufferOffset);
    // Serialize message field [success]
    bufferOffset = _serializer.bool(obj.success, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PickupResult
    let len;
    let data = new PickupResult(null);
    // Deserialize message field [executionSuccess]
    data.executionSuccess = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [success]
    data.success = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rail_manipulation_msgs/PickupResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5255cc5d9729cec7fd7524dffc953153';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    bool executionSuccess   # True if the arm could successfully complete motion planning
    bool success            # True if the object is verified to be in the gripper after pickup
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PickupResult(null);
    if (msg.executionSuccess !== undefined) {
      resolved.executionSuccess = msg.executionSuccess;
    }
    else {
      resolved.executionSuccess = false
    }

    if (msg.success !== undefined) {
      resolved.success = msg.success;
    }
    else {
      resolved.success = false
    }

    return resolved;
    }
};

module.exports = PickupResult;
