// Generated by gencpp from file rail_agile_grasp_msgs/ChangePointCloud.msg
// DO NOT EDIT!


#ifndef RAIL_AGILE_GRASP_MSGS_MESSAGE_CHANGEPOINTCLOUD_H
#define RAIL_AGILE_GRASP_MSGS_MESSAGE_CHANGEPOINTCLOUD_H

#include <ros/service_traits.h>


#include <rail_agile_grasp_msgs/ChangePointCloudRequest.h>
#include <rail_agile_grasp_msgs/ChangePointCloudResponse.h>


namespace rail_agile_grasp_msgs
{

struct ChangePointCloud
{

typedef ChangePointCloudRequest Request;
typedef ChangePointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangePointCloud
} // namespace rail_agile_grasp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloud > {
  static const char* value()
  {
    return "30e9301ca5c1fe846d8cf6adfc2fa80f";
  }

  static const char* value(const ::rail_agile_grasp_msgs::ChangePointCloud&) { return value(); }
};

template<>
struct DataType< ::rail_agile_grasp_msgs::ChangePointCloud > {
  static const char* value()
  {
    return "rail_agile_grasp_msgs/ChangePointCloud";
  }

  static const char* value(const ::rail_agile_grasp_msgs::ChangePointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloudRequest> should match 
// service_traits::MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloud > 
template<>
struct MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloud >::value();
  }
  static const char* value(const ::rail_agile_grasp_msgs::ChangePointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rail_agile_grasp_msgs::ChangePointCloudRequest> should match 
// service_traits::DataType< ::rail_agile_grasp_msgs::ChangePointCloud > 
template<>
struct DataType< ::rail_agile_grasp_msgs::ChangePointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::rail_agile_grasp_msgs::ChangePointCloud >::value();
  }
  static const char* value(const ::rail_agile_grasp_msgs::ChangePointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloudResponse> should match 
// service_traits::MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloud > 
template<>
struct MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rail_agile_grasp_msgs::ChangePointCloud >::value();
  }
  static const char* value(const ::rail_agile_grasp_msgs::ChangePointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rail_agile_grasp_msgs::ChangePointCloudResponse> should match 
// service_traits::DataType< ::rail_agile_grasp_msgs::ChangePointCloud > 
template<>
struct DataType< ::rail_agile_grasp_msgs::ChangePointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::rail_agile_grasp_msgs::ChangePointCloud >::value();
  }
  static const char* value(const ::rail_agile_grasp_msgs::ChangePointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAIL_AGILE_GRASP_MSGS_MESSAGE_CHANGEPOINTCLOUD_H
