// Auto-generated. Do not edit!

// (in-package rail_agile_grasp_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FindGraspsFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_action = null;
    }
    else {
      if (initObj.hasOwnProperty('current_action')) {
        this.current_action = initObj.current_action
      }
      else {
        this.current_action = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FindGraspsFeedback
    // Serialize message field [current_action]
    bufferOffset = _serializer.string(obj.current_action, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FindGraspsFeedback
    let len;
    let data = new FindGraspsFeedback(null);
    // Deserialize message field [current_action]
    data.current_action = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.current_action.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rail_agile_grasp_msgs/FindGraspsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a0b6ef05977891f85ef93fc8a715325c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    string current_action                       # text feedback indicating what's currently being executed
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FindGraspsFeedback(null);
    if (msg.current_action !== undefined) {
      resolved.current_action = msg.current_action;
    }
    else {
      resolved.current_action = ''
    }

    return resolved;
    }
};

module.exports = FindGraspsFeedback;
