// Auto-generated. Do not edit!

// (in-package rail_agile_grasp_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let rail_manipulation_msgs = _finder('rail_manipulation_msgs');
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class RailAgileGraspGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.do_segment = null;
      this.do_pickup = null;
      this.do_one = null;
      this.segmented_object_list = null;
      this.store_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('do_segment')) {
        this.do_segment = initObj.do_segment
      }
      else {
        this.do_segment = false;
      }
      if (initObj.hasOwnProperty('do_pickup')) {
        this.do_pickup = initObj.do_pickup
      }
      else {
        this.do_pickup = false;
      }
      if (initObj.hasOwnProperty('do_one')) {
        this.do_one = initObj.do_one
      }
      else {
        this.do_one = false;
      }
      if (initObj.hasOwnProperty('segmented_object_list')) {
        this.segmented_object_list = initObj.segmented_object_list
      }
      else {
        this.segmented_object_list = new rail_manipulation_msgs.msg.SegmentedObjectList();
      }
      if (initObj.hasOwnProperty('store_pose')) {
        this.store_pose = initObj.store_pose
      }
      else {
        this.store_pose = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RailAgileGraspGoal
    // Serialize message field [do_segment]
    bufferOffset = _serializer.bool(obj.do_segment, buffer, bufferOffset);
    // Serialize message field [do_pickup]
    bufferOffset = _serializer.bool(obj.do_pickup, buffer, bufferOffset);
    // Serialize message field [do_one]
    bufferOffset = _serializer.bool(obj.do_one, buffer, bufferOffset);
    // Serialize message field [segmented_object_list]
    bufferOffset = rail_manipulation_msgs.msg.SegmentedObjectList.serialize(obj.segmented_object_list, buffer, bufferOffset);
    // Serialize message field [store_pose]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.store_pose, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RailAgileGraspGoal
    let len;
    let data = new RailAgileGraspGoal(null);
    // Deserialize message field [do_segment]
    data.do_segment = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [do_pickup]
    data.do_pickup = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [do_one]
    data.do_one = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [segmented_object_list]
    data.segmented_object_list = rail_manipulation_msgs.msg.SegmentedObjectList.deserialize(buffer, bufferOffset);
    // Deserialize message field [store_pose]
    data.store_pose = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += rail_manipulation_msgs.msg.SegmentedObjectList.getMessageSize(object.segmented_object_list);
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.store_pose);
    return length + 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rail_agile_grasp_msgs/RailAgileGraspGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f3bdf6412e7802172116610ff2549dd1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    
    # if scene is not segmented, set do_segment to true. Otherwise, provides segmented object in segmented_object_list
    bool do_segment
    # set to true if want to use grasps generated by agile to pickup and store in store_pose
    bool do_pickup
    # set to true will only pickup the first object
    bool do_one
    rail_manipulation_msgs/SegmentedObjectList segmented_object_list
    geometry_msgs/PoseStamped store_pose
    
    
    ================================================================================
    MSG: rail_manipulation_msgs/SegmentedObjectList
    Header header              # Contains timestamp information for the most recent update to the object list
    bool cleared               # A flag indicating this message is the result of a clear instead of a segment
    SegmentedObject[] objects  # The list of segmented objects
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: rail_manipulation_msgs/SegmentedObject
    sensor_msgs/PointCloud2 point_cloud   # Segmented point cloud
    sensor_msgs/Image image               # Segmented RGB image
    geometry_msgs/Point centroid          # Centroid of the point cloud
    geometry_msgs/Point center            # Center of the point cloud
    float64 width                         # The width of the object in meters
    float64 depth                         # The depth of the object in meters
    float64 height                        # The height of the object in meters
    geometry_msgs/Quaternion orientation  # Orientation of the object (typically only known for recognized objects)
    bool recognized                       # True if the object is recognized
    string name                           # Object name (if recognized)
    uint32 model_id                       # Object model ID (if recognized)
    float64 confidence                    # Recognition confidence value
    Grasp[] grasps                        # List of grasps (if recognized)
    visualization_msgs/Marker marker      # The downsampled visualization of the object
    
    
    ================================================================================
    MSG: sensor_msgs/PointCloud2
    # This message holds a collection of N-dimensional points, which may
    # contain additional information such as normals, intensity, etc. The
    # point data is stored as a binary blob, its layout described by the
    # contents of the "fields" array.
    
    # The point cloud data may be organized 2d (image-like) or 1d
    # (unordered). Point clouds organized as 2d images may be produced by
    # camera depth sensors such as stereo or time-of-flight.
    
    # Time of sensor data acquisition, and the coordinate frame ID (for 3d
    # points).
    Header header
    
    # 2D structure of the point cloud. If the cloud is unordered, height is
    # 1 and width is the length of the point cloud.
    uint32 height
    uint32 width
    
    # Describes the channels and their layout in the binary data blob.
    PointField[] fields
    
    bool    is_bigendian # Is this data bigendian?
    uint32  point_step   # Length of a point in bytes
    uint32  row_step     # Length of a row in bytes
    uint8[] data         # Actual point data, size is (row_step*height)
    
    bool is_dense        # True if there are no invalid points
    
    ================================================================================
    MSG: sensor_msgs/PointField
    # This message holds the description of one point entry in the
    # PointCloud2 message format.
    uint8 INT8    = 1
    uint8 UINT8   = 2
    uint8 INT16   = 3
    uint8 UINT16  = 4
    uint8 INT32   = 5
    uint8 UINT32  = 6
    uint8 FLOAT32 = 7
    uint8 FLOAT64 = 8
    
    string name      # Name of field
    uint32 offset    # Offset from start of point struct
    uint8  datatype  # Datatype enumeration, see above
    uint32 count     # How many elements in the field
    
    ================================================================================
    MSG: sensor_msgs/Image
    # This message contains an uncompressed image
    # (0, 0) is at top-left corner of image
    #
    
    Header header        # Header timestamp should be acquisition time of image
                         # Header frame_id should be optical frame of camera
                         # origin of frame should be optical center of cameara
                         # +x should point to the right in the image
                         # +y should point down in the image
                         # +z should point into to plane of the image
                         # If the frame_id here and the frame_id of the CameraInfo
                         # message associated with the image conflict
                         # the behavior is undefined
    
    uint32 height         # image height, that is, number of rows
    uint32 width          # image width, that is, number of columns
    
    # The legal values for encoding are in file src/image_encodings.cpp
    # If you want to standardize a new string format, join
    # ros-users@lists.sourceforge.net and send an email proposing a new encoding.
    
    string encoding       # Encoding of pixels -- channel meaning, ordering, size
                          # taken from the list of strings in include/sensor_msgs/image_encodings.h
    
    uint8 is_bigendian    # is this data bigendian?
    uint32 step           # Full row length in bytes
    uint8[] data          # actual matrix data, size is (step * rows)
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: rail_manipulation_msgs/Grasp
    geometry_msgs/PoseStamped grasp_pose  # The grasp pose
    string eef_frame_id                   # The coordinate frame of the end-effector used by this grasp
    uint32 grasp_id
    uint32 successes                      # The number of recorded times this grasp was successful (useful for success rate)
    uint32 attempts                       # The number of recorded times this grasp was attempted (useful for success rate)
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: visualization_msgs/Marker
    # See http://www.ros.org/wiki/rviz/DisplayTypes/Marker and http://www.ros.org/wiki/rviz/Tutorials/Markers%3A%20Basic%20Shapes for more information on using this message with rviz
    
    uint8 ARROW=0
    uint8 CUBE=1
    uint8 SPHERE=2
    uint8 CYLINDER=3
    uint8 LINE_STRIP=4
    uint8 LINE_LIST=5
    uint8 CUBE_LIST=6
    uint8 SPHERE_LIST=7
    uint8 POINTS=8
    uint8 TEXT_VIEW_FACING=9
    uint8 MESH_RESOURCE=10
    uint8 TRIANGLE_LIST=11
    
    uint8 ADD=0
    uint8 MODIFY=0
    uint8 DELETE=2
    uint8 DELETEALL=3
    
    Header header                        # header for time/frame information
    string ns                            # Namespace to place this object in... used in conjunction with id to create a unique name for the object
    int32 id 		                         # object ID useful in conjunction with the namespace for manipulating and deleting the object later
    int32 type 		                       # Type of object
    int32 action 	                       # 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects
    geometry_msgs/Pose pose                 # Pose of the object
    geometry_msgs/Vector3 scale             # Scale of the object 1,1,1 means default (usually 1 meter square)
    std_msgs/ColorRGBA color             # Color [0.0-1.0]
    duration lifetime                    # How long the object should last before being automatically deleted.  0 means forever
    bool frame_locked                    # If this marker should be frame-locked, i.e. retransformed into its frame every timestep
    
    #Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...)
    geometry_msgs/Point[] points
    #Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...)
    #number of colors must either be 0 or equal to the number of points
    #NOTE: alpha is not yet used
    std_msgs/ColorRGBA[] colors
    
    # NOTE: only used for text markers
    string text
    
    # NOTE: only used for MESH_RESOURCE markers
    string mesh_resource
    bool mesh_use_embedded_materials
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    ================================================================================
    MSG: std_msgs/ColorRGBA
    float32 r
    float32 g
    float32 b
    float32 a
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RailAgileGraspGoal(null);
    if (msg.do_segment !== undefined) {
      resolved.do_segment = msg.do_segment;
    }
    else {
      resolved.do_segment = false
    }

    if (msg.do_pickup !== undefined) {
      resolved.do_pickup = msg.do_pickup;
    }
    else {
      resolved.do_pickup = false
    }

    if (msg.do_one !== undefined) {
      resolved.do_one = msg.do_one;
    }
    else {
      resolved.do_one = false
    }

    if (msg.segmented_object_list !== undefined) {
      resolved.segmented_object_list = rail_manipulation_msgs.msg.SegmentedObjectList.Resolve(msg.segmented_object_list)
    }
    else {
      resolved.segmented_object_list = new rail_manipulation_msgs.msg.SegmentedObjectList()
    }

    if (msg.store_pose !== undefined) {
      resolved.store_pose = geometry_msgs.msg.PoseStamped.Resolve(msg.store_pose)
    }
    else {
      resolved.store_pose = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = RailAgileGraspGoal;
