// Generated by gencpp from file rail_manipulation_msgs/GraspingState.msg
// DO NOT EDIT!


#ifndef RAIL_MANIPULATION_MSGS_MESSAGE_GRASPINGSTATE_H
#define RAIL_MANIPULATION_MSGS_MESSAGE_GRASPINGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rail_manipulation_msgs
{
template <class ContainerAllocator>
struct GraspingState_
{
  typedef GraspingState_<ContainerAllocator> Type;

  GraspingState_()
    : object_in_gripper(false)
    , object_name()  {
    }
  GraspingState_(const ContainerAllocator& _alloc)
    : object_in_gripper(false)
    , object_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _object_in_gripper_type;
  _object_in_gripper_type object_in_gripper;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;




  typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> const> ConstPtr;

}; // struct GraspingState_

typedef ::rail_manipulation_msgs::GraspingState_<std::allocator<void> > GraspingState;

typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspingState > GraspingStatePtr;
typedef boost::shared_ptr< ::rail_manipulation_msgs::GraspingState const> GraspingStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rail_manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rail_manipulation_msgs': ['/home/orsteam/SummerProject/src/rail_manipulation_msgs/msg', '/home/orsteam/SummerProject/devel/share/rail_manipulation_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a13c2818bf8b302fb88a9eb9ee906ba0";
  }

  static const char* value(const ::rail_manipulation_msgs::GraspingState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa13c2818bf8b302fULL;
  static const uint64_t static_value2 = 0xb88a9eb9ee906ba0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rail_manipulation_msgs/GraspingState";
  }

  static const char* value(const ::rail_manipulation_msgs::GraspingState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool object_in_gripper  # True if an object is in the gripper\n\
string object_name      # Name of the object in the gripper, if object_in_gripper is true\n\
";
  }

  static const char* value(const ::rail_manipulation_msgs::GraspingState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_in_gripper);
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspingState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rail_manipulation_msgs::GraspingState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rail_manipulation_msgs::GraspingState_<ContainerAllocator>& v)
  {
    s << indent << "object_in_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.object_in_gripper);
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAIL_MANIPULATION_MSGS_MESSAGE_GRASPINGSTATE_H
