// Generated by gencpp from file rail_manipulation_msgs/PrepareGrasp.msg
// DO NOT EDIT!


#ifndef RAIL_MANIPULATION_MSGS_MESSAGE_PREPAREGRASP_H
#define RAIL_MANIPULATION_MSGS_MESSAGE_PREPAREGRASP_H

#include <ros/service_traits.h>


#include <rail_manipulation_msgs/PrepareGraspRequest.h>
#include <rail_manipulation_msgs/PrepareGraspResponse.h>


namespace rail_manipulation_msgs
{

struct PrepareGrasp
{

typedef PrepareGraspRequest Request;
typedef PrepareGraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PrepareGrasp
} // namespace rail_manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rail_manipulation_msgs::PrepareGrasp > {
  static const char* value()
  {
    return "8918ac08fe533980834453f23389b29a";
  }

  static const char* value(const ::rail_manipulation_msgs::PrepareGrasp&) { return value(); }
};

template<>
struct DataType< ::rail_manipulation_msgs::PrepareGrasp > {
  static const char* value()
  {
    return "rail_manipulation_msgs/PrepareGrasp";
  }

  static const char* value(const ::rail_manipulation_msgs::PrepareGrasp&) { return value(); }
};


// service_traits::MD5Sum< ::rail_manipulation_msgs::PrepareGraspRequest> should match 
// service_traits::MD5Sum< ::rail_manipulation_msgs::PrepareGrasp > 
template<>
struct MD5Sum< ::rail_manipulation_msgs::PrepareGraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rail_manipulation_msgs::PrepareGrasp >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::PrepareGraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rail_manipulation_msgs::PrepareGraspRequest> should match 
// service_traits::DataType< ::rail_manipulation_msgs::PrepareGrasp > 
template<>
struct DataType< ::rail_manipulation_msgs::PrepareGraspRequest>
{
  static const char* value()
  {
    return DataType< ::rail_manipulation_msgs::PrepareGrasp >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::PrepareGraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rail_manipulation_msgs::PrepareGraspResponse> should match 
// service_traits::MD5Sum< ::rail_manipulation_msgs::PrepareGrasp > 
template<>
struct MD5Sum< ::rail_manipulation_msgs::PrepareGraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rail_manipulation_msgs::PrepareGrasp >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::PrepareGraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rail_manipulation_msgs::PrepareGraspResponse> should match 
// service_traits::DataType< ::rail_manipulation_msgs::PrepareGrasp > 
template<>
struct DataType< ::rail_manipulation_msgs::PrepareGraspResponse>
{
  static const char* value()
  {
    return DataType< ::rail_manipulation_msgs::PrepareGrasp >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::PrepareGraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAIL_MANIPULATION_MSGS_MESSAGE_PREPAREGRASP_H
