; Auto-generated. Do not edit!


(cl:in-package rail_agile_grasp_msgs-msg)


;//! \htmlinclude FindGraspsResult.msg.html

(cl:defclass <FindGraspsResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass FindGraspsResult (<FindGraspsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindGraspsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindGraspsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rail_agile_grasp_msgs-msg:<FindGraspsResult> is deprecated: use rail_agile_grasp_msgs-msg:FindGraspsResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <FindGraspsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rail_agile_grasp_msgs-msg:success-val is deprecated.  Use rail_agile_grasp_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindGraspsResult>) ostream)
  "Serializes a message object of type '<FindGraspsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindGraspsResult>) istream)
  "Deserializes a message object of type '<FindGraspsResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindGraspsResult>)))
  "Returns string type for a message object of type '<FindGraspsResult>"
  "rail_agile_grasp_msgs/FindGraspsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindGraspsResult)))
  "Returns string type for a message object of type 'FindGraspsResult"
  "rail_agile_grasp_msgs/FindGraspsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindGraspsResult>)))
  "Returns md5sum for a message object of type '<FindGraspsResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindGraspsResult)))
  "Returns md5sum for a message object of type 'FindGraspsResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindGraspsResult>)))
  "Returns full string definition for message of type '<FindGraspsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool success                                # true if AGILE is able to fully execute the find grasps routine~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindGraspsResult)))
  "Returns full string definition for message of type 'FindGraspsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool success                                # true if AGILE is able to fully execute the find grasps routine~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindGraspsResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindGraspsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FindGraspsResult
    (cl:cons ':success (success msg))
))
