; Auto-generated. Do not edit!


(cl:in-package rail_agile_grasp_msgs-msg)


;//! \htmlinclude RailAgileGraspFeedback.msg.html

(cl:defclass <RailAgileGraspFeedback> (roslisp-msg-protocol:ros-message)
  ((current_action
    :reader current_action
    :initarg :current_action
    :type cl:string
    :initform ""))
)

(cl:defclass RailAgileGraspFeedback (<RailAgileGraspFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RailAgileGraspFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RailAgileGraspFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rail_agile_grasp_msgs-msg:<RailAgileGraspFeedback> is deprecated: use rail_agile_grasp_msgs-msg:RailAgileGraspFeedback instead.")))

(cl:ensure-generic-function 'current_action-val :lambda-list '(m))
(cl:defmethod current_action-val ((m <RailAgileGraspFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rail_agile_grasp_msgs-msg:current_action-val is deprecated.  Use rail_agile_grasp_msgs-msg:current_action instead.")
  (current_action m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RailAgileGraspFeedback>) ostream)
  "Serializes a message object of type '<RailAgileGraspFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'current_action))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'current_action))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RailAgileGraspFeedback>) istream)
  "Deserializes a message object of type '<RailAgileGraspFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_action) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'current_action) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RailAgileGraspFeedback>)))
  "Returns string type for a message object of type '<RailAgileGraspFeedback>"
  "rail_agile_grasp_msgs/RailAgileGraspFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RailAgileGraspFeedback)))
  "Returns string type for a message object of type 'RailAgileGraspFeedback"
  "rail_agile_grasp_msgs/RailAgileGraspFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RailAgileGraspFeedback>)))
  "Returns md5sum for a message object of type '<RailAgileGraspFeedback>"
  "a0b6ef05977891f85ef93fc8a715325c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RailAgileGraspFeedback)))
  "Returns md5sum for a message object of type 'RailAgileGraspFeedback"
  "a0b6ef05977891f85ef93fc8a715325c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RailAgileGraspFeedback>)))
  "Returns full string definition for message of type '<RailAgileGraspFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Define a feedback message~%string current_action~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RailAgileGraspFeedback)))
  "Returns full string definition for message of type 'RailAgileGraspFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Define a feedback message~%string current_action~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RailAgileGraspFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'current_action))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RailAgileGraspFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RailAgileGraspFeedback
    (cl:cons ':current_action (current_action msg))
))
