(cl:defpackage remote_manipulation_markers-srv
  (:use )
  (:export
   "CREATESPHERE"
   "<CREATESPHERE-REQUEST>"
   "CREATESPHERE-REQUEST"
   "<CREATESPHERE-RESPONSE>"
   "CREATESPHERE-RESPONSE"
   "CYCLEGRASPS"
   "<CYCLEGRASPS-REQUEST>"
   "CYCLEGRASPS-REQUEST"
   "<CYCLEGRASPS-RESPONSE>"
   "CYCLEGRASPS-RESPONSE"
   "EXECUTEARM"
   "<EXECUTEARM-REQUEST>"
   "EXECUTEARM-REQUEST"
   "<EXECUTEARM-RESPONSE>"
   "EXECUTEARM-RESPONSE"
   "MODESWITCH"
   "<MODESWITCH-REQUEST>"
   "MODESWITCH-REQUEST"
   "<MODESWITCH-RESPONSE>"
   "MODESWITCH-RESPONSE"
  ))

