(cl:in-package rail_manipulation_msgs-msg)
(cl:export '(POINT_CLOUD-VAL
          POINT_CLOUD
          IMAGE-VAL
          IMAGE
          CENTROID-VAL
          CENTROID
          CENTER-VAL
          CENTER
          WIDTH-VAL
          WIDTH
          DEPTH-VAL
          DEPTH
          HEIGHT-VAL
          HEIGHT
          ORIENTATION-VAL
          ORIENTATION
          RECOGNIZED-VAL
          RECOGNIZED
          NAME-VAL
          NAME
          MODEL_ID-VAL
          MODEL_ID
          CONFIDENCE-VAL
          CONFIDENCE
          GRASPS-VAL
          GRASPS
          MARKER-VAL
          MARKER
))