; Auto-generated. Do not edit!


(cl:in-package rail_manipulation_msgs-msg)


;//! \htmlinclude LiftGoal.msg.html

(cl:defclass <LiftGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LiftGoal (<LiftGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LiftGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LiftGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rail_manipulation_msgs-msg:<LiftGoal> is deprecated: use rail_manipulation_msgs-msg:LiftGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LiftGoal>) ostream)
  "Serializes a message object of type '<LiftGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LiftGoal>) istream)
  "Deserializes a message object of type '<LiftGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LiftGoal>)))
  "Returns string type for a message object of type '<LiftGoal>"
  "rail_manipulation_msgs/LiftGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LiftGoal)))
  "Returns string type for a message object of type 'LiftGoal"
  "rail_manipulation_msgs/LiftGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LiftGoal>)))
  "Returns md5sum for a message object of type '<LiftGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LiftGoal)))
  "Returns md5sum for a message object of type 'LiftGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LiftGoal>)))
  "Returns full string definition for message of type '<LiftGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LiftGoal)))
  "Returns full string definition for message of type 'LiftGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LiftGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LiftGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LiftGoal
))
