; Auto-generated. Do not edit!


(cl:in-package rail_manipulation_msgs-msg)


;//! \htmlinclude PrimitiveResult.msg.html

(cl:defclass <PrimitiveResult> (roslisp-msg-protocol:ros-message)
  ((completion
    :reader completion
    :initarg :completion
    :type cl:float
    :initform 0.0))
)

(cl:defclass PrimitiveResult (<PrimitiveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PrimitiveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PrimitiveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rail_manipulation_msgs-msg:<PrimitiveResult> is deprecated: use rail_manipulation_msgs-msg:PrimitiveResult instead.")))

(cl:ensure-generic-function 'completion-val :lambda-list '(m))
(cl:defmethod completion-val ((m <PrimitiveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rail_manipulation_msgs-msg:completion-val is deprecated.  Use rail_manipulation_msgs-msg:completion instead.")
  (completion m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PrimitiveResult>) ostream)
  "Serializes a message object of type '<PrimitiveResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'completion))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PrimitiveResult>) istream)
  "Deserializes a message object of type '<PrimitiveResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'completion) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PrimitiveResult>)))
  "Returns string type for a message object of type '<PrimitiveResult>"
  "rail_manipulation_msgs/PrimitiveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PrimitiveResult)))
  "Returns string type for a message object of type 'PrimitiveResult"
  "rail_manipulation_msgs/PrimitiveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PrimitiveResult>)))
  "Returns md5sum for a message object of type '<PrimitiveResult>"
  "625ff476bf5a3a8ab489ab09eae43fe9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PrimitiveResult)))
  "Returns md5sum for a message object of type 'PrimitiveResult"
  "625ff476bf5a3a8ab489ab09eae43fe9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PrimitiveResult>)))
  "Returns full string definition for message of type '<PrimitiveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float64 completion      # percentage of the primitive action completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PrimitiveResult)))
  "Returns full string definition for message of type 'PrimitiveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float64 completion      # percentage of the primitive action completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PrimitiveResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PrimitiveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PrimitiveResult
    (cl:cons ':completion (completion msg))
))
