; Auto-generated. Do not edit!


(cl:in-package rail_manipulation_msgs-msg)


;//! \htmlinclude StoreResult.msg.html

(cl:defclass <StoreResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass StoreResult (<StoreResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StoreResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StoreResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rail_manipulation_msgs-msg:<StoreResult> is deprecated: use rail_manipulation_msgs-msg:StoreResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <StoreResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rail_manipulation_msgs-msg:success-val is deprecated.  Use rail_manipulation_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StoreResult>) ostream)
  "Serializes a message object of type '<StoreResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StoreResult>) istream)
  "Deserializes a message object of type '<StoreResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StoreResult>)))
  "Returns string type for a message object of type '<StoreResult>"
  "rail_manipulation_msgs/StoreResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StoreResult)))
  "Returns string type for a message object of type 'StoreResult"
  "rail_manipulation_msgs/StoreResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StoreResult>)))
  "Returns md5sum for a message object of type '<StoreResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StoreResult)))
  "Returns md5sum for a message object of type 'StoreResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StoreResult>)))
  "Returns full string definition for message of type '<StoreResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success  # True on successful store~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StoreResult)))
  "Returns full string definition for message of type 'StoreResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success  # True on successful store~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StoreResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StoreResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StoreResult
    (cl:cons ':success (success msg))
))
