# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rail_manipulation_msgs/PrimitiveGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PrimitiveGoal(genpy.Message):
  _md5sum = "c76a07691fd7d25efb98e8b7f78daf49"
  _type = "rail_manipulation_msgs/PrimitiveGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define the goal

#actions
uint8 TRANSLATION=0
uint8 ROTATION=1

#axes
uint8 X_AXIS=0
uint8 Y_AXIS=1
uint8 Z_AXIS=2

uint8 primitive_type    # type of primitive action
uint8 axis              # axis of translation/rotation
float64 distance        # distance to perform the action (in m or rad)
"""
  # Pseudo-constants
  TRANSLATION = 0
  ROTATION = 1
  X_AXIS = 0
  Y_AXIS = 1
  Z_AXIS = 2

  __slots__ = ['primitive_type','axis','distance']
  _slot_types = ['uint8','uint8','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       primitive_type,axis,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PrimitiveGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.primitive_type is None:
        self.primitive_type = 0
      if self.axis is None:
        self.axis = 0
      if self.distance is None:
        self.distance = 0.
    else:
      self.primitive_type = 0
      self.axis = 0
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd().pack(_x.primitive_type, _x.axis, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.primitive_type, _x.axis, _x.distance,) = _get_struct_2Bd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd().pack(_x.primitive_type, _x.axis, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.primitive_type, _x.axis, _x.distance,) = _get_struct_2Bd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bd = None
def _get_struct_2Bd():
    global _struct_2Bd
    if _struct_2Bd is None:
        _struct_2Bd = struct.Struct("<2Bd")
    return _struct_2Bd
